services:
  # Название нашего сервиса
  proxy-fountain:
    # Указываем, что нужно собрать образ из текущей директории, используя Dockerfile
    build: .
    # Имя контейнера для удобства
    container_name: proxy-fountain-app
    # Политика перезапуска: всегда перезапускать, если не был остановлен вручную.
    # Это обеспечивает автозапуск после перезагрузки хост-машины.
    restart: unless-stopped
    
    # Проброс портов: порт_на_хосте:порт_в_контейнере
    # Мы берем порт из вашего config.yaml
    ports:
      - "9999:9999" # Убедитесь, что порт совпадает с 'api_port' в config.yaml
      
    # Монтирование файлов и папок (самая важная часть!)
    volumes:
      # Прокидываем файл конфига с хоста внутрь контейнера.
      # Вы можете редактировать config.yaml на хосте, и приложение увидит изменения.
      - ./config.yaml:/app/config.yaml
      
      # Прокидываем папку для логов.
      # Лог-файлы будут появляться на вашем хосте в папке ./logs
      - ./logs:/app/logs